# -*- coding: utf-8 -*-
"""Heart_EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/152eF3_JcSr2yd1O8eu45kE8NhEa70cuU
"""

import pandas as pd

url = 'https://raw.githubusercontent.com/BradleyConlin/Kaggle/main/heart.csv'
df = pd.read_csv(url, index_col=0)
print(df.head(10))
